import 'package:flutter/material.dart';

const Color kBg = Color(0xFF050505);
const Color kSurface = Color(0xFF0A0A0A);
const Color kSurface2 = Color(0xFF111118);
const Color kSurface3 = Color(0xFF161624);
const Color kPrimary = Color(0xFF8A2BE2);
const Color kSecondary = Color(0xFFB026FF);
const Color kAccent = Color(0xFF6F00FF);
const Color kNeon = Color(0xFFCC66FF);
const Color kCyan = Color(0xFF00D4FF);
const Color kText = Color(0xFFFFFFFF);
const Color kTextDim = Color(0xFF9B9B9B);
const Color kTextMuted = Color(0xFF555566);
const Color kGlass = Color(0x12FFFFFF);
const Color kGlass2 = Color(0x08FFFFFF);
const Color kGlassBorder = Color(0x33CC66FF);
const Color kGlassBorder2 = Color(0x1ACC66FF);
const Color kError = Color(0xFFFF2E63);
const Color kSuccess = Color(0xFF00FF88);
const Color kWarning = Color(0xFFFFB800);
const Color kInfo = Color(0xFF00D4FF);

class AppColors {
  static const List<Color> gradientPrimary = [Color(0xFF8A2BE2), Color(0xFF6F00FF)];
  static const List<Color> gradientSecondary = [Color(0xFFB026FF), Color(0xFF8A2BE2)];
  static const List<Color> gradientNeon = [Color(0xFFCC66FF), Color(0xFF8A2BE2)];
  static const List<Color> gradientCyan = [Color(0xFF00D4FF), Color(0xFF6F00FF)];
  static const List<Color> gradientFire = [Color(0xFFFF2E63), Color(0xFFB026FF)];
  static const List<Color> gradientSuccess = [Color(0xFF00FF88), Color(0xFF00D4FF)];
  static const List<Color> gradientGold = [Color(0xFFFFB800), Color(0xFFFF6B00)];
  static const List<Color> gradientDark = [Color(0xFF111118), Color(0xFF050505)];
}

class Spacing {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 24;
  static const double xl = 32;
  static const double xxl = 48;
  static const double r4 = 4;
  static const double r8 = 8;
  static const double r12 = 12;
  static const double r16 = 16;
  static const double r20 = 20;
  static const double r24 = 24;
  static const double r32 = 32;
}

const Map<String, Map<String, String>> kLangStrings = {
  'en': {
    'app_name': 'CipherGuard',
    'dashboard': 'Dashboard',
    'vault': 'Vault',
    'security': 'Security',
    'info': 'Info',
    'security_overview': 'SECURITY OVERVIEW',
    'welcome': 'Welcome',
    'unlock_vault': 'UNLOCK VAULT',
    'authenticating': 'AUTHENTICATING...',
    'master_password': 'Master Password',
    'auth_required': 'AUTHENTICATION REQUIRED',
    'greeting': 'Hello',
    'settings': 'SETTINGS',
    'language': 'Language',
    'full_name': 'Full Name',
    'country': 'Country',
    'preferred_language': 'Preferred Language',
    'get_started': 'GET STARTED',
    'next': 'NEXT',
    'back': 'BACK',
    'complete': 'COMPLETE SETUP',
    'choose_protection': 'CHOOSE YOUR\nPROTECTION',
    'select_auth': 'SELECT YOUR AUTHENTICATION METHODS',
    'initialize': 'INITIALIZE CIPHERGUARD',
    'developer': 'Developer',
    'portfolio': 'Portfolio',
    'contact': 'Contact',
    'skills': 'Skills',
    'about_dev': 'About Developer',
    'add_entry': 'ADD ENTRY',
    'search': 'Search...',
    'no_items': 'Vault is empty',
    'add_first': 'Add your first secure item',
    'weak_passwords': 'Weak Passwords',
    'duplicate_passwords': 'Duplicate Passwords',
    'at_risk': 'At-Risk Items',
    'threat_analysis': 'THREAT ANALYSIS',
    'encryption_details': 'ENCRYPTION DETAILS',
    'audit_log': 'AUDIT LOG',
  },
  'fa': {
    'app_name': 'سایفرگارد',
    'dashboard': 'داشبورد',
    'vault': 'خزانه',
    'security': 'امنیت',
    'info': 'اطلاعات',
    'security_overview': 'نمای کلی امنیت',
    'welcome': 'خوش آمدید',
    'unlock_vault': 'باز کردن خزانه',
    'authenticating': 'در حال احراز هویت...',
    'master_password': 'رمز عبور اصلی',
    'auth_required': 'احراز هویت الزامی است',
    'greeting': 'سلام',
    'settings': 'تنظیمات',
    'language': 'زبان',
    'full_name': 'نام کامل',
    'country': 'کشور',
    'preferred_language': 'زبان ترجیحی',
    'get_started': 'شروع کنید',
    'next': 'بعدی',
    'back': 'قبلی',
    'complete': 'تکمیل راه‌اندازی',
    'choose_protection': 'روش\nمحافظت خود را انتخاب کنید',
    'select_auth': 'روش‌های احراز هویت خود را انتخاب کنید',
    'initialize': 'راه‌اندازی سایفرگارد',
    'developer': 'توسعه‌دهنده',
    'portfolio': 'نمونه‌کارها',
    'contact': 'تماس',
    'skills': 'مهارت‌ها',
    'about_dev': 'درباره توسعه‌دهنده',
    'add_entry': 'افزودن مورد',
    'search': 'جستجو...',
    'no_items': 'خزانه خالی است',
    'add_first': 'اولین مورد امن خود را اضافه کنید',
    'weak_passwords': 'رمزهای ضعیف',
    'duplicate_passwords': 'رمزهای تکراری',
    'at_risk': 'موارد در معرض خطر',
    'threat_analysis': 'تحلیل تهدیدات',
    'encryption_details': 'جزئیات رمزنگاری',
    'audit_log': 'گزارش حسابرسی',
  },
  'ar': {
    'app_name': 'سايفرغارد',
    'dashboard': 'لوحة القيادة',
    'vault': 'الخزينة',
    'security': 'الأمان',
    'info': 'المعلومات',
    'security_overview': 'نظرة عامة على الأمان',
    'welcome': 'مرحباً',
    'unlock_vault': 'فتح الخزينة',
    'authenticating': 'جارٍ التحقق...',
    'master_password': 'كلمة المرور الرئيسية',
    'auth_required': 'المصادقة مطلوبة',
    'greeting': 'مرحباً',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'full_name': 'الاسم الكامل',
    'country': 'الدولة',
    'preferred_language': 'اللغة المفضلة',
    'get_started': 'ابدأ الآن',
    'next': 'التالي',
    'back': 'السابق',
    'complete': 'إتمام الإعداد',
    'choose_protection': 'اختر\nطريقة الحماية',
    'select_auth': 'اختر طرق المصادقة',
    'initialize': 'تهيئة سايفرغارد',
    'developer': 'المطور',
    'portfolio': 'معرض الأعمال',
    'contact': 'التواصل',
    'skills': 'المهارات',
    'about_dev': 'عن المطور',
    'add_entry': 'إضافة إدخال',
    'search': 'بحث...',
    'no_items': 'الخزينة فارغة',
    'add_first': 'أضف أول عنصر آمن لديك',
    'weak_passwords': 'كلمات المرور الضعيفة',
    'duplicate_passwords': 'كلمات المرور المكررة',
    'at_risk': 'العناصر المعرضة للخطر',
    'threat_analysis': 'تحليل التهديدات',
    'encryption_details': 'تفاصيل التشفير',
    'audit_log': 'سجل التدقيق',
  },
  'tr': {
    'app_name': 'CipherGuard',
    'dashboard': 'Gösterge',
    'vault': 'Kasa',
    'security': 'Güvenlik',
    'info': 'Bilgi',
    'security_overview': 'GÜVENLİK GÖRÜNÜMÜ',
    'welcome': 'Hoş Geldiniz',
    'unlock_vault': 'KASAYI AÇ',
    'authenticating': 'KİMLİK DOĞRULANYOR...',
    'master_password': 'Ana Parola',
    'auth_required': 'KİMLİK DOĞRULAMA GEREKLİ',
    'greeting': 'Merhaba',
    'settings': 'AYARLAR',
    'language': 'Dil',
    'full_name': 'Ad Soyad',
    'country': 'Ülke',
    'preferred_language': 'Tercih Edilen Dil',
    'get_started': 'BAŞLA',
    'next': 'İLERİ',
    'back': 'GERİ',
    'complete': 'KURULUMU TAMAMLA',
    'choose_protection': 'KORUMA\nYÖNTEMİNİZİ SEÇİN',
    'select_auth': 'KİMLİK DOĞRULAMA YÖNTEMLERİNİZİ SEÇİN',
    'initialize': 'CIPHERGUARD\'I BAŞLAT',
    'developer': 'Geliştirici',
    'portfolio': 'Portfolyo',
    'contact': 'İletişim',
    'skills': 'Beceriler',
    'about_dev': 'Geliştirici Hakkında',
    'add_entry': 'GİRİŞ EKLE',
    'search': 'Ara...',
    'no_items': 'Kasa boş',
    'add_first': 'İlk güvenli öğenizi ekleyin',
    'weak_passwords': 'Zayıf Parolalar',
    'duplicate_passwords': 'Yinelenen Parolalar',
    'at_risk': 'Risk Altındaki Öğeler',
    'threat_analysis': 'TEHDİT ANALİZİ',
    'encryption_details': 'ŞİFRELEME DETAYLARI',
    'audit_log': 'DENETİM GÜNLÜĞÜ',
  },
  'ru': {
    'app_name': 'CipherGuard',
    'dashboard': 'Панель',
    'vault': 'Хранилище',
    'security': 'Безопасность',
    'info': 'Инфо',
    'security_overview': 'ОБЗОР БЕЗОПАСНОСТИ',
    'welcome': 'Добро пожаловать',
    'unlock_vault': 'ОТКРЫТЬ ХРАНИЛИЩЕ',
    'authenticating': 'АУТЕНТИФИКАЦИЯ...',
    'master_password': 'Мастер-пароль',
    'auth_required': 'ТРЕБУЕТСЯ АУТЕНТИФИКАЦИЯ',
    'greeting': 'Привет',
    'settings': 'НАСТРОЙКИ',
    'language': 'Язык',
    'full_name': 'Полное имя',
    'country': 'Страна',
    'preferred_language': 'Предпочитаемый язык',
    'get_started': 'НАЧАТЬ',
    'next': 'ДАЛЕЕ',
    'back': 'НАЗАД',
    'complete': 'ЗАВЕРШИТЬ НАСТРОЙКУ',
    'choose_protection': 'ВЫБЕРИТЕ\nМЕТОД ЗАЩИТЫ',
    'select_auth': 'ВЫБЕРИТЕ МЕТОДЫ АУТЕНТИФИКАЦИИ',
    'initialize': 'ИНИЦИАЛИЗИРОВАТЬ CIPHERGUARD',
    'developer': 'Разработчик',
    'portfolio': 'Портфолио',
    'contact': 'Контакты',
    'skills': 'Навыки',
    'about_dev': 'О разработчике',
    'add_entry': 'ДОБАВИТЬ',
    'search': 'Поиск...',
    'no_items': 'Хранилище пусто',
    'add_first': 'Добавьте первый защищённый элемент',
    'weak_passwords': 'Слабые пароли',
    'duplicate_passwords': 'Повторяющиеся пароли',
    'at_risk': 'Уязвимые элементы',
    'threat_analysis': 'АНАЛИЗ УГРОЗ',
    'encryption_details': 'СВЕДЕНИЯ О ШИФРОВАНИИ',
    'audit_log': 'ЖУРНАЛ АУДИТА',
  },
  'de': {
    'app_name': 'CipherGuard',
    'dashboard': 'Dashboard',
    'vault': 'Tresor',
    'security': 'Sicherheit',
    'info': 'Info',
    'security_overview': 'SICHERHEITSÜBERSICHT',
    'welcome': 'Willkommen',
    'unlock_vault': 'TRESOR ÖFFNEN',
    'authenticating': 'AUTHENTIFIZIERUNG...',
    'master_password': 'Master-Passwort',
    'auth_required': 'AUTHENTIFIZIERUNG ERFORDERLICH',
    'greeting': 'Hallo',
    'settings': 'EINSTELLUNGEN',
    'language': 'Sprache',
    'full_name': 'Vollständiger Name',
    'country': 'Land',
    'preferred_language': 'Bevorzugte Sprache',
    'get_started': 'LOSLEGEN',
    'next': 'WEITER',
    'back': 'ZURÜCK',
    'complete': 'SETUP ABSCHLIESSEN',
    'choose_protection': 'SCHUTZ\nAUSWÄHLEN',
    'select_auth': 'AUTHENTIFIZIERUNGSMETHODEN WÄHLEN',
    'initialize': 'CIPHERGUARD INITIALISIEREN',
    'developer': 'Entwickler',
    'portfolio': 'Portfolio',
    'contact': 'Kontakt',
    'skills': 'Fähigkeiten',
    'about_dev': 'Über den Entwickler',
    'add_entry': 'EINTRAG HINZUFÜGEN',
    'search': 'Suchen...',
    'no_items': 'Tresor ist leer',
    'add_first': 'Fügen Sie Ihr erstes Element hinzu',
    'weak_passwords': 'Schwache Passwörter',
    'duplicate_passwords': 'Doppelte Passwörter',
    'at_risk': 'Gefährdete Elemente',
    'threat_analysis': 'BEDROHUNGSANALYSE',
    'encryption_details': 'VERSCHLÜSSELUNGSDETAILS',
    'audit_log': 'PRÜFPROTOKOLL',
  },
  'fr': {
    'app_name': 'CipherGuard',
    'dashboard': 'Tableau',
    'vault': 'Coffre',
    'security': 'Sécurité',
    'info': 'Info',
    'security_overview': 'APERÇU DE SÉCURITÉ',
    'welcome': 'Bienvenue',
    'unlock_vault': 'OUVRIR LE COFFRE',
    'authenticating': 'AUTHENTIFICATION...',
    'master_password': 'Mot de passe maître',
    'auth_required': 'AUTHENTIFICATION REQUISE',
    'greeting': 'Bonjour',
    'settings': 'PARAMÈTRES',
    'language': 'Langue',
    'full_name': 'Nom complet',
    'country': 'Pays',
    'preferred_language': 'Langue préférée',
    'get_started': 'COMMENCER',
    'next': 'SUIVANT',
    'back': 'RETOUR',
    'complete': 'TERMINER LA CONFIGURATION',
    'choose_protection': 'CHOISIR\nLA PROTECTION',
    'select_auth': 'SÉLECTIONNEZ VOS MÉTHODES D\'AUTHENTIFICATION',
    'initialize': 'INITIALISER CIPHERGUARD',
    'developer': 'Développeur',
    'portfolio': 'Portfolio',
    'contact': 'Contact',
    'skills': 'Compétences',
    'about_dev': 'À propos du développeur',
    'add_entry': 'AJOUTER',
    'search': 'Rechercher...',
    'no_items': 'Coffre vide',
    'add_first': 'Ajoutez votre premier élément sécurisé',
    'weak_passwords': 'Mots de passe faibles',
    'duplicate_passwords': 'Mots de passe dupliqués',
    'at_risk': 'Éléments à risque',
    'threat_analysis': 'ANALYSE DES MENACES',
    'encryption_details': 'DÉTAILS DE CHIFFREMENT',
    'audit_log': 'JOURNAL D\'AUDIT',
  },
};

const List<Map<String, String>> kSupportedLanguages = [
  {'code': 'en', 'name': 'English', 'native': 'English', 'flag': '🇺🇸'},
  {'code': 'fa', 'name': 'Persian', 'native': 'فارسی', 'flag': '🇮🇷'},
  {'code': 'ar', 'name': 'Arabic', 'native': 'العربية', 'flag': '🇸🇦'},
  {'code': 'tr', 'name': 'Turkish', 'native': 'Türkçe', 'flag': '🇹🇷'},
  {'code': 'ru', 'name': 'Russian', 'native': 'Русский', 'flag': '🇷🇺'},
  {'code': 'de', 'name': 'German', 'native': 'Deutsch', 'flag': '🇩🇪'},
  {'code': 'fr', 'name': 'French', 'native': 'Français', 'flag': '🇫🇷'},
];

const List<String> kCountries = [
  'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Australia',
  'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium',
  'Bolivia', 'Bosnia', 'Brazil', 'Bulgaria', 'Cambodia', 'Canada', 'Chile',
  'China', 'Colombia', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Ecuador', 'Egypt', 'Estonia', 'Ethiopia', 'Finland', 'France',
  'Georgia', 'Germany', 'Ghana', 'Greece', 'Hungary', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Italy', 'Japan', 'Jordan', 'Kazakhstan',
  'Kenya', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lebanon', 'Libya', 'Lithuania',
  'Luxembourg', 'Malaysia', 'Mexico', 'Moldova', 'Morocco', 'Netherlands',
  'New Zealand', 'Nigeria', 'North Korea', 'Norway', 'Oman', 'Pakistan',
  'Palestine', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
  'Russia', 'Saudi Arabia', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia',
  'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden',
  'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand', 'Tunisia',
  'Turkey', 'Turkmenistan', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
  'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Yemen',
];
